/*
  ==============================================================================

    TypeName.h
    Created: 4 Jan 2026 7:44:25pm
    Author:  Matkat Music LLC

  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>

//#include <typeinfo>
//#include <memory>

#if defined(__clang__) || defined(__GNUC__)
 #include <cxxabi.h>
#endif

/*
 This code gets the deduced type from a template parameter
 Generated by [AI]
 */
namespace detail
{
template <class T>
constexpr std::string_view type_name()
{
#if defined(__clang__) || defined(__GNUC__)
    std::string_view p = __PRETTY_FUNCTION__;
    auto start = p.find("T = ");
    auto end   = p.rfind("]");
//    std::cout << p << std::endl;
    return p.substr(start + 4, end - (start + 4));
#elif defined(_MSC_VER)
    std::string_view p = __FUNCSIG__;
    auto start = p.find("type_name<");
    auto end   = p.rfind(">(void)");
    return p.substr(start + 10, end - (start + 10));
#else
    return "unknown-compiler";
#endif
}

} //end namespace detail

#define TYPE_NAME(T) (::detail::type_name<T>())

template<typename T>
inline juce::String GetClassName()
{
#if defined(__clang__) || defined(__GNUC__)
    const char* mangled = typeid(T).name();
    int status = 0;
    // abi::__cxa_demangle allocates with malloc; we'll wrap it in a unique_ptr for RAII
    std::unique_ptr<char, void(*)(void*)> demangledBuf(
        abi::__cxa_demangle(mangled, nullptr, nullptr, &status),
        [](void* p) { if (p) std::free(p); }
    );

    if (status == 0 && demangledBuf)
        return juce::String(demangledBuf.get());
    else
        return juce::String(mangled);
#else
    return juce::String(typeid(T).name());
#endif
}

