/*
  ==============================================================================

    TypeName.h
    Created: 4 Jan 2026 7:44:25pm
    Author:  Matkat Music LLC

  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>

/*
 This code gets the deduced type from a template parameter
 Generated by [AI]
 */
namespace detail
{
template <class T>
constexpr std::string_view type_name()
{
#if defined(__clang__) || defined(__GNUC__)
    std::string_view p = __PRETTY_FUNCTION__;
    auto start = p.find("T = ");
    auto end   = p.rfind("]");
//    std::cout << p << std::endl;
    return p.substr(start + 4, end - (start + 4));
#elif defined(_MSC_VER)
    std::string_view p = __FUNCSIG__;
    auto start = p.find("type_name<");
    auto end   = p.rfind(">(void)");
    return p.substr(start + 10, end - (start + 10));
#else
    return "unknown-compiler";
#endif
}

} //end namespace detail

#define TYPE_NAME(T) (::detail::type_name<T>())
